
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'AppFooter': typeof import("../../app/components/app/footer.vue")['default']
  'AppHeader': typeof import("../../app/components/app/header.vue")['default']
  'AppHomepageHeader': typeof import("../../app/components/app/homepage-header.vue")['default']
  'AuthLoginForm': typeof import("../../app/components/auth/login-form.vue")['default']
  'CommonLanguageSwitcher': typeof import("../../app/components/common/language-switcher.vue")['default']
  'ContactMessageForm': typeof import("../../app/components/contact/message-form.vue")['default']
  'DashboardSidebarMenu': typeof import("../../app/components/dashboard/sidebar-menu.vue")['default']
  'DashboardUserDropdown': typeof import("../../app/components/dashboard/user-dropdown.vue")['default']
  'GalleryCollectionGrid': typeof import("../../app/components/gallery/collection-grid.vue")['default']
  'GalleryDetailDialog': typeof import("../../app/components/gallery/detail-dialog.vue")['default']
  'GalleryDetailImageGrid': typeof import("../../app/components/gallery/detail-image-grid.vue")['default']
  'GalleryFilterButton': typeof import("../../app/components/gallery/filter-button.vue")['default']
  'GalleryDetailHero': typeof import("../../app/components/gallery/gallery-detail-hero.vue")['default']
  'GalleryHeaderFilter': typeof import("../../app/components/gallery/header-filter.vue")['default']
  'GalleryHeader': typeof import("../../app/components/gallery/header.vue")['default']
  'GalleryPagination': typeof import("../../app/components/gallery/pagination.vue")['default']
  'HomepageHeroCarousel': typeof import("../../app/components/homepage/hero-carousel.vue")['default']
  'IconInstagram': typeof import("../../app/components/icon/instagram.vue")['default']
  'IconInstagram1': typeof import("../../app/components/icon/instagram1.vue")['default']
  'IconInstagram2': typeof import("../../app/components/icon/instagram2.vue")['default']
  'IconInstagram3': typeof import("../../app/components/icon/instagram3.vue")['default']
  'IconTelegram': typeof import("../../app/components/icon/telegram.vue")['default']
  'IconTiktok': typeof import("../../app/components/icon/tiktok.vue")['default']
  'IconWhatsapp': typeof import("../../app/components/icon/whatsapp.vue")['default']
  'ManageAboutContent': typeof import("../../app/components/manage-about/content.vue")['default']
  'ManageAboutForm': typeof import("../../app/components/manage-about/form.vue")['default']
  'ManageAboutSchema': typeof import("../../app/components/manage-about/schema")['default']
  'ManageAboutTable': typeof import("../../app/components/manage-about/table.vue")['default']
  'ManageCategoryContent': typeof import("../../app/components/manage-category/content.vue")['default']
  'ManageCategoryForm': typeof import("../../app/components/manage-category/form.vue")['default']
  'ManageCategorySchema': typeof import("../../app/components/manage-category/schema")['default']
  'ManageCategoryTable': typeof import("../../app/components/manage-category/table.vue")['default']
  'ManageGalleryDetailContent': typeof import("../../app/components/manage-gallery-detail/content.vue")['default']
  'ManageGalleryDetailForm': typeof import("../../app/components/manage-gallery-detail/form.vue")['default']
  'ManageGalleryDetailSchema': typeof import("../../app/components/manage-gallery-detail/schema")['default']
  'ManageGalleryDetailTable': typeof import("../../app/components/manage-gallery-detail/table.vue")['default']
  'ManageGalleryContent': typeof import("../../app/components/manage-gallery/content.vue")['default']
  'ManageGalleryForm': typeof import("../../app/components/manage-gallery/form.vue")['default']
  'ManageGallerySchema': typeof import("../../app/components/manage-gallery/schema")['default']
  'ManageGalleryTable': typeof import("../../app/components/manage-gallery/table.vue")['default']
  'ManageSocialMediaContent': typeof import("../../app/components/manage-social-media/content.vue")['default']
  'ManageSocialMediaForm': typeof import("../../app/components/manage-social-media/form.vue")['default']
  'ManageSocialMediaSchema': typeof import("../../app/components/manage-social-media/schema")['default']
  'UiVueSonner': typeof import("../../app/components/ui/VueSonner.client.vue")['default']
  'UiAccordion': typeof import("../../app/components/ui/accordion/accordion.vue")['default']
  'UiAccordionContent': typeof import("../../app/components/ui/accordion/content.vue")['default']
  'UiAccordionHeader': typeof import("../../app/components/ui/accordion/header.vue")['default']
  'UiAccordionItem': typeof import("../../app/components/ui/accordion/item.vue")['default']
  'UiAccordionTrigger': typeof import("../../app/components/ui/accordion/trigger.vue")['default']
  'UiAutoCompleteAnchor': typeof import("../../app/components/ui/auto-complete/anchor.vue")['default']
  'UiAutoCompleteArrow': typeof import("../../app/components/ui/auto-complete/arrow.vue")['default']
  'UiAutoComplete': typeof import("../../app/components/ui/auto-complete/auto-complete.vue")['default']
  'UiAutoCompleteCancel': typeof import("../../app/components/ui/auto-complete/cancel.vue")['default']
  'UiAutoCompleteContent': typeof import("../../app/components/ui/auto-complete/content.vue")['default']
  'UiAutoCompleteEmpty': typeof import("../../app/components/ui/auto-complete/empty.vue")['default']
  'UiAutoCompleteGroup': typeof import("../../app/components/ui/auto-complete/group.vue")['default']
  'UiAutoCompleteInput': typeof import("../../app/components/ui/auto-complete/input.vue")['default']
  'UiAutoCompleteItemIndicator': typeof import("../../app/components/ui/auto-complete/item-indicator.vue")['default']
  'UiAutoCompleteItem': typeof import("../../app/components/ui/auto-complete/item.vue")['default']
  'UiAutoCompleteLabel': typeof import("../../app/components/ui/auto-complete/label.vue")['default']
  'UiAutoCompletePortal': typeof import("../../app/components/ui/auto-complete/portal.vue")['default']
  'UiAutoCompleteSeparator': typeof import("../../app/components/ui/auto-complete/separator.vue")['default']
  'UiAutoCompleteTrigger': typeof import("../../app/components/ui/auto-complete/trigger.vue")['default']
  'UiAutoCompleteViewport': typeof import("../../app/components/ui/auto-complete/viewport.vue")['default']
  'UiBreadcrumbs': typeof import("../../app/components/ui/breadcrumbs.vue")['default']
  'UiButton': typeof import("../../app/components/ui/button.vue")['default']
  'UiCard': typeof import("../../app/components/ui/card/card.vue")['default']
  'UiCardContent': typeof import("../../app/components/ui/card/content.vue")['default']
  'UiCardDescription': typeof import("../../app/components/ui/card/description.vue")['default']
  'UiCardFooter': typeof import("../../app/components/ui/card/footer.vue")['default']
  'UiCardHeader': typeof import("../../app/components/ui/card/header.vue")['default']
  'UiCardTitle': typeof import("../../app/components/ui/card/title.vue")['default']
  'UiCategorySelect': typeof import("../../app/components/ui/category-select.client.vue")['default']
  'UiCommandCancel': typeof import("../../app/components/ui/command/cancel.vue")['default']
  'UiCommand': typeof import("../../app/components/ui/command/command.vue")['default']
  'UiCommandDialog': typeof import("../../app/components/ui/command/dialog.vue")['default']
  'UiCommandEmpty': typeof import("../../app/components/ui/command/empty.vue")['default']
  'UiCommandGroup': typeof import("../../app/components/ui/command/group.vue")['default']
  'UiCommandInput': typeof import("../../app/components/ui/command/input.vue")['default']
  'UiCommandItem': typeof import("../../app/components/ui/command/item.vue")['default']
  'UiCommandLabel': typeof import("../../app/components/ui/command/label.vue")['default']
  'UiCommandList': typeof import("../../app/components/ui/command/list.vue")['default']
  'UiCommandSeparator': typeof import("../../app/components/ui/command/separator.vue")['default']
  'UiCommandShortcut': typeof import("../../app/components/ui/command/shortcut.vue")['default']
  'UiConfirmDialog': typeof import("../../app/components/ui/confirm-dialog.client.vue")['default']
  'UiContainer': typeof import("../../app/components/ui/container.vue")['default']
  'UiDialogClose': typeof import("../../app/components/ui/dialog/close.vue")['default']
  'UiDialogContent': typeof import("../../app/components/ui/dialog/content.vue")['default']
  'UiDialogDescription': typeof import("../../app/components/ui/dialog/description.vue")['default']
  'UiDialog': typeof import("../../app/components/ui/dialog/dialog.vue")['default']
  'UiDialogFooter': typeof import("../../app/components/ui/dialog/footer.vue")['default']
  'UiDialogHeader': typeof import("../../app/components/ui/dialog/header.vue")['default']
  'UiDialogOverlay': typeof import("../../app/components/ui/dialog/overlay.vue")['default']
  'UiDialogPortal': typeof import("../../app/components/ui/dialog/portal.vue")['default']
  'UiDialogTitle': typeof import("../../app/components/ui/dialog/title.vue")['default']
  'UiDialogTrigger': typeof import("../../app/components/ui/dialog/trigger.vue")['default']
  'UiDropdownMenuArrow': typeof import("../../app/components/ui/dropdown-menu/arrow.vue")['default']
  'UiDropdownMenuCheckboxItem': typeof import("../../app/components/ui/dropdown-menu/checkbox-item.vue")['default']
  'UiDropdownMenuContent': typeof import("../../app/components/ui/dropdown-menu/content.vue")['default']
  'UiDropdownMenu': typeof import("../../app/components/ui/dropdown-menu/dropdown-menu.vue")['default']
  'UiDropdownMenuGroup': typeof import("../../app/components/ui/dropdown-menu/group.vue")['default']
  'UiDropdownMenuItemIndicator': typeof import("../../app/components/ui/dropdown-menu/item-indicator.vue")['default']
  'UiDropdownMenuItem': typeof import("../../app/components/ui/dropdown-menu/item.vue")['default']
  'UiDropdownMenuLabel': typeof import("../../app/components/ui/dropdown-menu/label.vue")['default']
  'UiDropdownMenuPortal': typeof import("../../app/components/ui/dropdown-menu/portal.vue")['default']
  'UiDropdownMenuRadioGroup': typeof import("../../app/components/ui/dropdown-menu/radio-group.vue")['default']
  'UiDropdownMenuRadioItem': typeof import("../../app/components/ui/dropdown-menu/radio-item.vue")['default']
  'UiDropdownMenuSeparator': typeof import("../../app/components/ui/dropdown-menu/separator.vue")['default']
  'UiDropdownMenuShortcut': typeof import("../../app/components/ui/dropdown-menu/shortcut.vue")['default']
  'UiDropdownMenuSubContent': typeof import("../../app/components/ui/dropdown-menu/sub-content.vue")['default']
  'UiDropdownMenuSubTrigger': typeof import("../../app/components/ui/dropdown-menu/sub-trigger.vue")['default']
  'UiDropdownMenuSub': typeof import("../../app/components/ui/dropdown-menu/sub.vue")['default']
  'UiDropdownMenuTrigger': typeof import("../../app/components/ui/dropdown-menu/trigger.vue")['default']
  'UiDropfile': typeof import("../../app/components/ui/dropfile.vue")['default']
  'UiFormControl': typeof import("../../app/components/ui/form/control.vue")['default']
  'UiFormDescription': typeof import("../../app/components/ui/form/description.vue")['default']
  'UiFormFloatingItem': typeof import("../../app/components/ui/form/floating-item.vue")['default']
  'UiFormItem': typeof import("../../app/components/ui/form/item.vue")['default']
  'UiFormLabel': typeof import("../../app/components/ui/form/label.vue")['default']
  'UiFormMessage': typeof import("../../app/components/ui/form/message.vue")['default']
  'UiImagePreview': typeof import("../../app/components/ui/image-preview.vue")['default']
  'UiInput': typeof import("../../app/components/ui/input.vue")['default']
  'UiLabel': typeof import("../../app/components/ui/label.vue")['default']
  'UiNavbar': typeof import("../../app/components/ui/navbar.vue")['default']
  'UiPaginationNumberControl': typeof import("../../app/components/ui/pagination/number-control.vue")['default']
  'UiPagination': typeof import("../../app/components/ui/pagination/pagination.vue")['default']
  'UiPaginationPerPage': typeof import("../../app/components/ui/pagination/per-page.vue")['default']
  'UiPopoverAnchor': typeof import("../../app/components/ui/popover/anchor.vue")['default']
  'UiPopoverArrow': typeof import("../../app/components/ui/popover/arrow.vue")['default']
  'UiPopoverClose': typeof import("../../app/components/ui/popover/close.vue")['default']
  'UiPopoverContent': typeof import("../../app/components/ui/popover/content.vue")['default']
  'UiPopover': typeof import("../../app/components/ui/popover/popover.vue")['default']
  'UiPopoverPortal': typeof import("../../app/components/ui/popover/portal.vue")['default']
  'UiPopoverTrigger': typeof import("../../app/components/ui/popover/trigger.vue")['default']
  'UiPopoverX': typeof import("../../app/components/ui/popover/x.vue")['default']
  'UiSelectArrow': typeof import("../../app/components/ui/select/arrow.vue")['default']
  'UiSelectContent': typeof import("../../app/components/ui/select/content.vue")['default']
  'UiSelectGroup': typeof import("../../app/components/ui/select/group.vue")['default']
  'UiSelectIcon': typeof import("../../app/components/ui/select/icon.vue")['default']
  'UiSelectItemIndicator': typeof import("../../app/components/ui/select/item-indicator.vue")['default']
  'UiSelectItemText': typeof import("../../app/components/ui/select/item-text.vue")['default']
  'UiSelectItem': typeof import("../../app/components/ui/select/item.vue")['default']
  'UiSelectLabel': typeof import("../../app/components/ui/select/label.vue")['default']
  'UiSelectPortal': typeof import("../../app/components/ui/select/portal.vue")['default']
  'UiSelectScrollDownButton': typeof import("../../app/components/ui/select/scroll-down-button.vue")['default']
  'UiSelectScrollUpButton': typeof import("../../app/components/ui/select/scroll-up-button.vue")['default']
  'UiSelect': typeof import("../../app/components/ui/select/select.vue")['default']
  'UiSelectSeparator': typeof import("../../app/components/ui/select/separator.vue")['default']
  'UiSelectTrigger': typeof import("../../app/components/ui/select/trigger.vue")['default']
  'UiSelectValue': typeof import("../../app/components/ui/select/value.vue")['default']
  'UiSelectViewport': typeof import("../../app/components/ui/select/viewport.vue")['default']
  'UiSeparator': typeof import("../../app/components/ui/separator.vue")['default']
  'UiSheetClose': typeof import("../../app/components/ui/sheet/close.vue")['default']
  'UiSheetContent': typeof import("../../app/components/ui/sheet/content.vue")['default']
  'UiSheetDescription': typeof import("../../app/components/ui/sheet/description.vue")['default']
  'UiSheetFooter': typeof import("../../app/components/ui/sheet/footer.vue")['default']
  'UiSheetHeader': typeof import("../../app/components/ui/sheet/header.vue")['default']
  'UiSheetOverlay': typeof import("../../app/components/ui/sheet/overlay.vue")['default']
  'UiSheetPortal': typeof import("../../app/components/ui/sheet/portal.vue")['default']
  'UiSheet': typeof import("../../app/components/ui/sheet/sheet.vue")['default']
  'UiSheetTitle': typeof import("../../app/components/ui/sheet/title.vue")['default']
  'UiSheetTrigger': typeof import("../../app/components/ui/sheet/trigger.vue")['default']
  'UiSheetX': typeof import("../../app/components/ui/sheet/x.vue")['default']
  'UiSidebarContent': typeof import("../../app/components/ui/sidebar/content.vue")['default']
  'UiSidebarFooter': typeof import("../../app/components/ui/sidebar/footer.vue")['default']
  'UiSidebarGroupAction': typeof import("../../app/components/ui/sidebar/group-action.vue")['default']
  'UiSidebarGroupContent': typeof import("../../app/components/ui/sidebar/group-content.vue")['default']
  'UiSidebarGroupLabel': typeof import("../../app/components/ui/sidebar/group-label.vue")['default']
  'UiSidebarGroup': typeof import("../../app/components/ui/sidebar/group.vue")['default']
  'UiSidebarHeader': typeof import("../../app/components/ui/sidebar/header.vue")['default']
  'UiSidebarInput': typeof import("../../app/components/ui/sidebar/input.vue")['default']
  'UiSidebarInset': typeof import("../../app/components/ui/sidebar/inset.vue")['default']
  'UiSidebarMenuAction': typeof import("../../app/components/ui/sidebar/menu-action.vue")['default']
  'UiSidebarMenuBadge': typeof import("../../app/components/ui/sidebar/menu-badge.vue")['default']
  'UiSidebarMenuButtonChild': typeof import("../../app/components/ui/sidebar/menu-button-child.vue")['default']
  'UiSidebarMenuButton': typeof import("../../app/components/ui/sidebar/menu-button.vue")['default']
  'UiSidebarMenuItem': typeof import("../../app/components/ui/sidebar/menu-item.vue")['default']
  'UiSidebarMenuSkeleton': typeof import("../../app/components/ui/sidebar/menu-skeleton.vue")['default']
  'UiSidebarMenuSubButton': typeof import("../../app/components/ui/sidebar/menu-sub-button.vue")['default']
  'UiSidebarMenuSubItem': typeof import("../../app/components/ui/sidebar/menu-sub-item.vue")['default']
  'UiSidebarMenuSub': typeof import("../../app/components/ui/sidebar/menu-sub.vue")['default']
  'UiSidebarMenu': typeof import("../../app/components/ui/sidebar/menu.vue")['default']
  'UiSidebarProvider': typeof import("../../app/components/ui/sidebar/provider.vue")['default']
  'UiSidebarRail': typeof import("../../app/components/ui/sidebar/rail.vue")['default']
  'UiSidebarSeparator': typeof import("../../app/components/ui/sidebar/separator.vue")['default']
  'UiSidebar': typeof import("../../app/components/ui/sidebar/sidebar.vue")['default']
  'UiSidebarTrigger': typeof import("../../app/components/ui/sidebar/trigger.vue")['default']
  'UiTableAction': typeof import("../../app/components/ui/table/action.vue")['default']
  'UiTableContainer': typeof import("../../app/components/ui/table/container.vue")['default']
  'UiTableData': typeof import("../../app/components/ui/table/data.vue")['default']
  'UiTableHead': typeof import("../../app/components/ui/table/head.vue")['default']
  'UiTableRow': typeof import("../../app/components/ui/table/row.vue")['default']
  'UiTableSearch': typeof import("../../app/components/ui/table/search.vue")['default']
  'UiTable': typeof import("../../app/components/ui/table/table.vue")['default']
  'UiTextarea': typeof import("../../app/components/ui/textarea.vue")['default']
  'UiTiptap': typeof import("../../app/components/ui/tiptap.client.vue")['default']
  'UiTooltipArrow': typeof import("../../app/components/ui/tooltip/arrow.vue")['default']
  'UiTooltipContent': typeof import("../../app/components/ui/tooltip/content.vue")['default']
  'UiTooltipPortal': typeof import("../../app/components/ui/tooltip/portal.vue")['default']
  'UiTooltipProvider': typeof import("../../app/components/ui/tooltip/provider.vue")['default']
  'UiTooltip': typeof import("../../app/components/ui/tooltip/tooltip.vue")['default']
  'UiTooltipTrigger': typeof import("../../app/components/ui/tooltip/trigger.vue")['default']
  'NuxtWelcome': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/welcome.vue")['default']
  'NuxtLayout': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  'NuxtErrorBoundary': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  'ClientOnly': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/client-only")['default']
  'DevOnly': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/dev-only")['default']
  'ServerPlaceholder': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/server-placeholder")['default']
  'NuxtLink': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-link")['default']
  'NuxtLoadingIndicator': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  'NuxtTime': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  'NuxtRouteAnnouncer': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  'NuxtImg': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  'NuxtPicture': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  'Icon': typeof import("../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.3.5_vite@7.1.9_@types+node@24.10.1_jiti@2.6.1_lightningcss_d91a7470f0b7d900e7fd19ead4b8541a/node_modules/@nuxt/icon/dist/runtime/components/index")['default']
  'TiptapEditorContent': typeof import("@tiptap/vue-3")['EditorContent']
  'TiptapFloatingMenu': typeof import("@tiptap/vue-3")['FloatingMenu']
  'TiptapBubbleMenu': typeof import("@tiptap/vue-3")['BubbleMenu']
  'ErrorMessage': typeof import("vee-validate")['ErrorMessage']
  'Field': typeof import("vee-validate")['Field']
  'FieldArray': typeof import("vee-validate")['FieldArray']
  'Form': typeof import("vee-validate")['Form']
  'NuxtPage': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/pages/runtime/page")['default']
  'NoScript': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['NoScript']
  'Link': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Link']
  'Base': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Base']
  'Title': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Title']
  'Meta': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Meta']
  'Style': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Style']
  'Head': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Head']
  'Html': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Html']
  'Body': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Body']
  'NuxtIsland': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-island")['default']
  'LazyAppFooter': LazyComponent<typeof import("../../app/components/app/footer.vue")['default']>
  'LazyAppHeader': LazyComponent<typeof import("../../app/components/app/header.vue")['default']>
  'LazyAppHomepageHeader': LazyComponent<typeof import("../../app/components/app/homepage-header.vue")['default']>
  'LazyAuthLoginForm': LazyComponent<typeof import("../../app/components/auth/login-form.vue")['default']>
  'LazyCommonLanguageSwitcher': LazyComponent<typeof import("../../app/components/common/language-switcher.vue")['default']>
  'LazyContactMessageForm': LazyComponent<typeof import("../../app/components/contact/message-form.vue")['default']>
  'LazyDashboardSidebarMenu': LazyComponent<typeof import("../../app/components/dashboard/sidebar-menu.vue")['default']>
  'LazyDashboardUserDropdown': LazyComponent<typeof import("../../app/components/dashboard/user-dropdown.vue")['default']>
  'LazyGalleryCollectionGrid': LazyComponent<typeof import("../../app/components/gallery/collection-grid.vue")['default']>
  'LazyGalleryDetailDialog': LazyComponent<typeof import("../../app/components/gallery/detail-dialog.vue")['default']>
  'LazyGalleryDetailImageGrid': LazyComponent<typeof import("../../app/components/gallery/detail-image-grid.vue")['default']>
  'LazyGalleryFilterButton': LazyComponent<typeof import("../../app/components/gallery/filter-button.vue")['default']>
  'LazyGalleryDetailHero': LazyComponent<typeof import("../../app/components/gallery/gallery-detail-hero.vue")['default']>
  'LazyGalleryHeaderFilter': LazyComponent<typeof import("../../app/components/gallery/header-filter.vue")['default']>
  'LazyGalleryHeader': LazyComponent<typeof import("../../app/components/gallery/header.vue")['default']>
  'LazyGalleryPagination': LazyComponent<typeof import("../../app/components/gallery/pagination.vue")['default']>
  'LazyHomepageHeroCarousel': LazyComponent<typeof import("../../app/components/homepage/hero-carousel.vue")['default']>
  'LazyIconInstagram': LazyComponent<typeof import("../../app/components/icon/instagram.vue")['default']>
  'LazyIconInstagram1': LazyComponent<typeof import("../../app/components/icon/instagram1.vue")['default']>
  'LazyIconInstagram2': LazyComponent<typeof import("../../app/components/icon/instagram2.vue")['default']>
  'LazyIconInstagram3': LazyComponent<typeof import("../../app/components/icon/instagram3.vue")['default']>
  'LazyIconTelegram': LazyComponent<typeof import("../../app/components/icon/telegram.vue")['default']>
  'LazyIconTiktok': LazyComponent<typeof import("../../app/components/icon/tiktok.vue")['default']>
  'LazyIconWhatsapp': LazyComponent<typeof import("../../app/components/icon/whatsapp.vue")['default']>
  'LazyManageAboutContent': LazyComponent<typeof import("../../app/components/manage-about/content.vue")['default']>
  'LazyManageAboutForm': LazyComponent<typeof import("../../app/components/manage-about/form.vue")['default']>
  'LazyManageAboutSchema': LazyComponent<typeof import("../../app/components/manage-about/schema")['default']>
  'LazyManageAboutTable': LazyComponent<typeof import("../../app/components/manage-about/table.vue")['default']>
  'LazyManageCategoryContent': LazyComponent<typeof import("../../app/components/manage-category/content.vue")['default']>
  'LazyManageCategoryForm': LazyComponent<typeof import("../../app/components/manage-category/form.vue")['default']>
  'LazyManageCategorySchema': LazyComponent<typeof import("../../app/components/manage-category/schema")['default']>
  'LazyManageCategoryTable': LazyComponent<typeof import("../../app/components/manage-category/table.vue")['default']>
  'LazyManageGalleryDetailContent': LazyComponent<typeof import("../../app/components/manage-gallery-detail/content.vue")['default']>
  'LazyManageGalleryDetailForm': LazyComponent<typeof import("../../app/components/manage-gallery-detail/form.vue")['default']>
  'LazyManageGalleryDetailSchema': LazyComponent<typeof import("../../app/components/manage-gallery-detail/schema")['default']>
  'LazyManageGalleryDetailTable': LazyComponent<typeof import("../../app/components/manage-gallery-detail/table.vue")['default']>
  'LazyManageGalleryContent': LazyComponent<typeof import("../../app/components/manage-gallery/content.vue")['default']>
  'LazyManageGalleryForm': LazyComponent<typeof import("../../app/components/manage-gallery/form.vue")['default']>
  'LazyManageGallerySchema': LazyComponent<typeof import("../../app/components/manage-gallery/schema")['default']>
  'LazyManageGalleryTable': LazyComponent<typeof import("../../app/components/manage-gallery/table.vue")['default']>
  'LazyManageSocialMediaContent': LazyComponent<typeof import("../../app/components/manage-social-media/content.vue")['default']>
  'LazyManageSocialMediaForm': LazyComponent<typeof import("../../app/components/manage-social-media/form.vue")['default']>
  'LazyManageSocialMediaSchema': LazyComponent<typeof import("../../app/components/manage-social-media/schema")['default']>
  'LazyUiVueSonner': LazyComponent<typeof import("../../app/components/ui/VueSonner.client.vue")['default']>
  'LazyUiAccordion': LazyComponent<typeof import("../../app/components/ui/accordion/accordion.vue")['default']>
  'LazyUiAccordionContent': LazyComponent<typeof import("../../app/components/ui/accordion/content.vue")['default']>
  'LazyUiAccordionHeader': LazyComponent<typeof import("../../app/components/ui/accordion/header.vue")['default']>
  'LazyUiAccordionItem': LazyComponent<typeof import("../../app/components/ui/accordion/item.vue")['default']>
  'LazyUiAccordionTrigger': LazyComponent<typeof import("../../app/components/ui/accordion/trigger.vue")['default']>
  'LazyUiAutoCompleteAnchor': LazyComponent<typeof import("../../app/components/ui/auto-complete/anchor.vue")['default']>
  'LazyUiAutoCompleteArrow': LazyComponent<typeof import("../../app/components/ui/auto-complete/arrow.vue")['default']>
  'LazyUiAutoComplete': LazyComponent<typeof import("../../app/components/ui/auto-complete/auto-complete.vue")['default']>
  'LazyUiAutoCompleteCancel': LazyComponent<typeof import("../../app/components/ui/auto-complete/cancel.vue")['default']>
  'LazyUiAutoCompleteContent': LazyComponent<typeof import("../../app/components/ui/auto-complete/content.vue")['default']>
  'LazyUiAutoCompleteEmpty': LazyComponent<typeof import("../../app/components/ui/auto-complete/empty.vue")['default']>
  'LazyUiAutoCompleteGroup': LazyComponent<typeof import("../../app/components/ui/auto-complete/group.vue")['default']>
  'LazyUiAutoCompleteInput': LazyComponent<typeof import("../../app/components/ui/auto-complete/input.vue")['default']>
  'LazyUiAutoCompleteItemIndicator': LazyComponent<typeof import("../../app/components/ui/auto-complete/item-indicator.vue")['default']>
  'LazyUiAutoCompleteItem': LazyComponent<typeof import("../../app/components/ui/auto-complete/item.vue")['default']>
  'LazyUiAutoCompleteLabel': LazyComponent<typeof import("../../app/components/ui/auto-complete/label.vue")['default']>
  'LazyUiAutoCompletePortal': LazyComponent<typeof import("../../app/components/ui/auto-complete/portal.vue")['default']>
  'LazyUiAutoCompleteSeparator': LazyComponent<typeof import("../../app/components/ui/auto-complete/separator.vue")['default']>
  'LazyUiAutoCompleteTrigger': LazyComponent<typeof import("../../app/components/ui/auto-complete/trigger.vue")['default']>
  'LazyUiAutoCompleteViewport': LazyComponent<typeof import("../../app/components/ui/auto-complete/viewport.vue")['default']>
  'LazyUiBreadcrumbs': LazyComponent<typeof import("../../app/components/ui/breadcrumbs.vue")['default']>
  'LazyUiButton': LazyComponent<typeof import("../../app/components/ui/button.vue")['default']>
  'LazyUiCard': LazyComponent<typeof import("../../app/components/ui/card/card.vue")['default']>
  'LazyUiCardContent': LazyComponent<typeof import("../../app/components/ui/card/content.vue")['default']>
  'LazyUiCardDescription': LazyComponent<typeof import("../../app/components/ui/card/description.vue")['default']>
  'LazyUiCardFooter': LazyComponent<typeof import("../../app/components/ui/card/footer.vue")['default']>
  'LazyUiCardHeader': LazyComponent<typeof import("../../app/components/ui/card/header.vue")['default']>
  'LazyUiCardTitle': LazyComponent<typeof import("../../app/components/ui/card/title.vue")['default']>
  'LazyUiCategorySelect': LazyComponent<typeof import("../../app/components/ui/category-select.client.vue")['default']>
  'LazyUiCommandCancel': LazyComponent<typeof import("../../app/components/ui/command/cancel.vue")['default']>
  'LazyUiCommand': LazyComponent<typeof import("../../app/components/ui/command/command.vue")['default']>
  'LazyUiCommandDialog': LazyComponent<typeof import("../../app/components/ui/command/dialog.vue")['default']>
  'LazyUiCommandEmpty': LazyComponent<typeof import("../../app/components/ui/command/empty.vue")['default']>
  'LazyUiCommandGroup': LazyComponent<typeof import("../../app/components/ui/command/group.vue")['default']>
  'LazyUiCommandInput': LazyComponent<typeof import("../../app/components/ui/command/input.vue")['default']>
  'LazyUiCommandItem': LazyComponent<typeof import("../../app/components/ui/command/item.vue")['default']>
  'LazyUiCommandLabel': LazyComponent<typeof import("../../app/components/ui/command/label.vue")['default']>
  'LazyUiCommandList': LazyComponent<typeof import("../../app/components/ui/command/list.vue")['default']>
  'LazyUiCommandSeparator': LazyComponent<typeof import("../../app/components/ui/command/separator.vue")['default']>
  'LazyUiCommandShortcut': LazyComponent<typeof import("../../app/components/ui/command/shortcut.vue")['default']>
  'LazyUiConfirmDialog': LazyComponent<typeof import("../../app/components/ui/confirm-dialog.client.vue")['default']>
  'LazyUiContainer': LazyComponent<typeof import("../../app/components/ui/container.vue")['default']>
  'LazyUiDialogClose': LazyComponent<typeof import("../../app/components/ui/dialog/close.vue")['default']>
  'LazyUiDialogContent': LazyComponent<typeof import("../../app/components/ui/dialog/content.vue")['default']>
  'LazyUiDialogDescription': LazyComponent<typeof import("../../app/components/ui/dialog/description.vue")['default']>
  'LazyUiDialog': LazyComponent<typeof import("../../app/components/ui/dialog/dialog.vue")['default']>
  'LazyUiDialogFooter': LazyComponent<typeof import("../../app/components/ui/dialog/footer.vue")['default']>
  'LazyUiDialogHeader': LazyComponent<typeof import("../../app/components/ui/dialog/header.vue")['default']>
  'LazyUiDialogOverlay': LazyComponent<typeof import("../../app/components/ui/dialog/overlay.vue")['default']>
  'LazyUiDialogPortal': LazyComponent<typeof import("../../app/components/ui/dialog/portal.vue")['default']>
  'LazyUiDialogTitle': LazyComponent<typeof import("../../app/components/ui/dialog/title.vue")['default']>
  'LazyUiDialogTrigger': LazyComponent<typeof import("../../app/components/ui/dialog/trigger.vue")['default']>
  'LazyUiDropdownMenuArrow': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/arrow.vue")['default']>
  'LazyUiDropdownMenuCheckboxItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/checkbox-item.vue")['default']>
  'LazyUiDropdownMenuContent': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/content.vue")['default']>
  'LazyUiDropdownMenu': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/dropdown-menu.vue")['default']>
  'LazyUiDropdownMenuGroup': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/group.vue")['default']>
  'LazyUiDropdownMenuItemIndicator': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/item-indicator.vue")['default']>
  'LazyUiDropdownMenuItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/item.vue")['default']>
  'LazyUiDropdownMenuLabel': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/label.vue")['default']>
  'LazyUiDropdownMenuPortal': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/portal.vue")['default']>
  'LazyUiDropdownMenuRadioGroup': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/radio-group.vue")['default']>
  'LazyUiDropdownMenuRadioItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/radio-item.vue")['default']>
  'LazyUiDropdownMenuSeparator': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/separator.vue")['default']>
  'LazyUiDropdownMenuShortcut': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/shortcut.vue")['default']>
  'LazyUiDropdownMenuSubContent': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/sub-content.vue")['default']>
  'LazyUiDropdownMenuSubTrigger': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/sub-trigger.vue")['default']>
  'LazyUiDropdownMenuSub': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/sub.vue")['default']>
  'LazyUiDropdownMenuTrigger': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/trigger.vue")['default']>
  'LazyUiDropfile': LazyComponent<typeof import("../../app/components/ui/dropfile.vue")['default']>
  'LazyUiFormControl': LazyComponent<typeof import("../../app/components/ui/form/control.vue")['default']>
  'LazyUiFormDescription': LazyComponent<typeof import("../../app/components/ui/form/description.vue")['default']>
  'LazyUiFormFloatingItem': LazyComponent<typeof import("../../app/components/ui/form/floating-item.vue")['default']>
  'LazyUiFormItem': LazyComponent<typeof import("../../app/components/ui/form/item.vue")['default']>
  'LazyUiFormLabel': LazyComponent<typeof import("../../app/components/ui/form/label.vue")['default']>
  'LazyUiFormMessage': LazyComponent<typeof import("../../app/components/ui/form/message.vue")['default']>
  'LazyUiImagePreview': LazyComponent<typeof import("../../app/components/ui/image-preview.vue")['default']>
  'LazyUiInput': LazyComponent<typeof import("../../app/components/ui/input.vue")['default']>
  'LazyUiLabel': LazyComponent<typeof import("../../app/components/ui/label.vue")['default']>
  'LazyUiNavbar': LazyComponent<typeof import("../../app/components/ui/navbar.vue")['default']>
  'LazyUiPaginationNumberControl': LazyComponent<typeof import("../../app/components/ui/pagination/number-control.vue")['default']>
  'LazyUiPagination': LazyComponent<typeof import("../../app/components/ui/pagination/pagination.vue")['default']>
  'LazyUiPaginationPerPage': LazyComponent<typeof import("../../app/components/ui/pagination/per-page.vue")['default']>
  'LazyUiPopoverAnchor': LazyComponent<typeof import("../../app/components/ui/popover/anchor.vue")['default']>
  'LazyUiPopoverArrow': LazyComponent<typeof import("../../app/components/ui/popover/arrow.vue")['default']>
  'LazyUiPopoverClose': LazyComponent<typeof import("../../app/components/ui/popover/close.vue")['default']>
  'LazyUiPopoverContent': LazyComponent<typeof import("../../app/components/ui/popover/content.vue")['default']>
  'LazyUiPopover': LazyComponent<typeof import("../../app/components/ui/popover/popover.vue")['default']>
  'LazyUiPopoverPortal': LazyComponent<typeof import("../../app/components/ui/popover/portal.vue")['default']>
  'LazyUiPopoverTrigger': LazyComponent<typeof import("../../app/components/ui/popover/trigger.vue")['default']>
  'LazyUiPopoverX': LazyComponent<typeof import("../../app/components/ui/popover/x.vue")['default']>
  'LazyUiSelectArrow': LazyComponent<typeof import("../../app/components/ui/select/arrow.vue")['default']>
  'LazyUiSelectContent': LazyComponent<typeof import("../../app/components/ui/select/content.vue")['default']>
  'LazyUiSelectGroup': LazyComponent<typeof import("../../app/components/ui/select/group.vue")['default']>
  'LazyUiSelectIcon': LazyComponent<typeof import("../../app/components/ui/select/icon.vue")['default']>
  'LazyUiSelectItemIndicator': LazyComponent<typeof import("../../app/components/ui/select/item-indicator.vue")['default']>
  'LazyUiSelectItemText': LazyComponent<typeof import("../../app/components/ui/select/item-text.vue")['default']>
  'LazyUiSelectItem': LazyComponent<typeof import("../../app/components/ui/select/item.vue")['default']>
  'LazyUiSelectLabel': LazyComponent<typeof import("../../app/components/ui/select/label.vue")['default']>
  'LazyUiSelectPortal': LazyComponent<typeof import("../../app/components/ui/select/portal.vue")['default']>
  'LazyUiSelectScrollDownButton': LazyComponent<typeof import("../../app/components/ui/select/scroll-down-button.vue")['default']>
  'LazyUiSelectScrollUpButton': LazyComponent<typeof import("../../app/components/ui/select/scroll-up-button.vue")['default']>
  'LazyUiSelect': LazyComponent<typeof import("../../app/components/ui/select/select.vue")['default']>
  'LazyUiSelectSeparator': LazyComponent<typeof import("../../app/components/ui/select/separator.vue")['default']>
  'LazyUiSelectTrigger': LazyComponent<typeof import("../../app/components/ui/select/trigger.vue")['default']>
  'LazyUiSelectValue': LazyComponent<typeof import("../../app/components/ui/select/value.vue")['default']>
  'LazyUiSelectViewport': LazyComponent<typeof import("../../app/components/ui/select/viewport.vue")['default']>
  'LazyUiSeparator': LazyComponent<typeof import("../../app/components/ui/separator.vue")['default']>
  'LazyUiSheetClose': LazyComponent<typeof import("../../app/components/ui/sheet/close.vue")['default']>
  'LazyUiSheetContent': LazyComponent<typeof import("../../app/components/ui/sheet/content.vue")['default']>
  'LazyUiSheetDescription': LazyComponent<typeof import("../../app/components/ui/sheet/description.vue")['default']>
  'LazyUiSheetFooter': LazyComponent<typeof import("../../app/components/ui/sheet/footer.vue")['default']>
  'LazyUiSheetHeader': LazyComponent<typeof import("../../app/components/ui/sheet/header.vue")['default']>
  'LazyUiSheetOverlay': LazyComponent<typeof import("../../app/components/ui/sheet/overlay.vue")['default']>
  'LazyUiSheetPortal': LazyComponent<typeof import("../../app/components/ui/sheet/portal.vue")['default']>
  'LazyUiSheet': LazyComponent<typeof import("../../app/components/ui/sheet/sheet.vue")['default']>
  'LazyUiSheetTitle': LazyComponent<typeof import("../../app/components/ui/sheet/title.vue")['default']>
  'LazyUiSheetTrigger': LazyComponent<typeof import("../../app/components/ui/sheet/trigger.vue")['default']>
  'LazyUiSheetX': LazyComponent<typeof import("../../app/components/ui/sheet/x.vue")['default']>
  'LazyUiSidebarContent': LazyComponent<typeof import("../../app/components/ui/sidebar/content.vue")['default']>
  'LazyUiSidebarFooter': LazyComponent<typeof import("../../app/components/ui/sidebar/footer.vue")['default']>
  'LazyUiSidebarGroupAction': LazyComponent<typeof import("../../app/components/ui/sidebar/group-action.vue")['default']>
  'LazyUiSidebarGroupContent': LazyComponent<typeof import("../../app/components/ui/sidebar/group-content.vue")['default']>
  'LazyUiSidebarGroupLabel': LazyComponent<typeof import("../../app/components/ui/sidebar/group-label.vue")['default']>
  'LazyUiSidebarGroup': LazyComponent<typeof import("../../app/components/ui/sidebar/group.vue")['default']>
  'LazyUiSidebarHeader': LazyComponent<typeof import("../../app/components/ui/sidebar/header.vue")['default']>
  'LazyUiSidebarInput': LazyComponent<typeof import("../../app/components/ui/sidebar/input.vue")['default']>
  'LazyUiSidebarInset': LazyComponent<typeof import("../../app/components/ui/sidebar/inset.vue")['default']>
  'LazyUiSidebarMenuAction': LazyComponent<typeof import("../../app/components/ui/sidebar/menu-action.vue")['default']>
  'LazyUiSidebarMenuBadge': LazyComponent<typeof import("../../app/components/ui/sidebar/menu-badge.vue")['default']>
  'LazyUiSidebarMenuButtonChild': LazyComponent<typeof import("../../app/components/ui/sidebar/menu-button-child.vue")['default']>
  'LazyUiSidebarMenuButton': LazyComponent<typeof import("../../app/components/ui/sidebar/menu-button.vue")['default']>
  'LazyUiSidebarMenuItem': LazyComponent<typeof import("../../app/components/ui/sidebar/menu-item.vue")['default']>
  'LazyUiSidebarMenuSkeleton': LazyComponent<typeof import("../../app/components/ui/sidebar/menu-skeleton.vue")['default']>
  'LazyUiSidebarMenuSubButton': LazyComponent<typeof import("../../app/components/ui/sidebar/menu-sub-button.vue")['default']>
  'LazyUiSidebarMenuSubItem': LazyComponent<typeof import("../../app/components/ui/sidebar/menu-sub-item.vue")['default']>
  'LazyUiSidebarMenuSub': LazyComponent<typeof import("../../app/components/ui/sidebar/menu-sub.vue")['default']>
  'LazyUiSidebarMenu': LazyComponent<typeof import("../../app/components/ui/sidebar/menu.vue")['default']>
  'LazyUiSidebarProvider': LazyComponent<typeof import("../../app/components/ui/sidebar/provider.vue")['default']>
  'LazyUiSidebarRail': LazyComponent<typeof import("../../app/components/ui/sidebar/rail.vue")['default']>
  'LazyUiSidebarSeparator': LazyComponent<typeof import("../../app/components/ui/sidebar/separator.vue")['default']>
  'LazyUiSidebar': LazyComponent<typeof import("../../app/components/ui/sidebar/sidebar.vue")['default']>
  'LazyUiSidebarTrigger': LazyComponent<typeof import("../../app/components/ui/sidebar/trigger.vue")['default']>
  'LazyUiTableAction': LazyComponent<typeof import("../../app/components/ui/table/action.vue")['default']>
  'LazyUiTableContainer': LazyComponent<typeof import("../../app/components/ui/table/container.vue")['default']>
  'LazyUiTableData': LazyComponent<typeof import("../../app/components/ui/table/data.vue")['default']>
  'LazyUiTableHead': LazyComponent<typeof import("../../app/components/ui/table/head.vue")['default']>
  'LazyUiTableRow': LazyComponent<typeof import("../../app/components/ui/table/row.vue")['default']>
  'LazyUiTableSearch': LazyComponent<typeof import("../../app/components/ui/table/search.vue")['default']>
  'LazyUiTable': LazyComponent<typeof import("../../app/components/ui/table/table.vue")['default']>
  'LazyUiTextarea': LazyComponent<typeof import("../../app/components/ui/textarea.vue")['default']>
  'LazyUiTiptap': LazyComponent<typeof import("../../app/components/ui/tiptap.client.vue")['default']>
  'LazyUiTooltipArrow': LazyComponent<typeof import("../../app/components/ui/tooltip/arrow.vue")['default']>
  'LazyUiTooltipContent': LazyComponent<typeof import("../../app/components/ui/tooltip/content.vue")['default']>
  'LazyUiTooltipPortal': LazyComponent<typeof import("../../app/components/ui/tooltip/portal.vue")['default']>
  'LazyUiTooltipProvider': LazyComponent<typeof import("../../app/components/ui/tooltip/provider.vue")['default']>
  'LazyUiTooltip': LazyComponent<typeof import("../../app/components/ui/tooltip/tooltip.vue")['default']>
  'LazyUiTooltipTrigger': LazyComponent<typeof import("../../app/components/ui/tooltip/trigger.vue")['default']>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/client-only")['default']>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/dev-only")['default']>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  'LazyIcon': LazyComponent<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.3.5_vite@7.1.9_@types+node@24.10.1_jiti@2.6.1_lightningcss_d91a7470f0b7d900e7fd19ead4b8541a/node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
  'LazyTiptapEditorContent': LazyComponent<typeof import("@tiptap/vue-3")['EditorContent']>
  'LazyTiptapFloatingMenu': LazyComponent<typeof import("@tiptap/vue-3")['FloatingMenu']>
  'LazyTiptapBubbleMenu': LazyComponent<typeof import("@tiptap/vue-3")['BubbleMenu']>
  'LazyErrorMessage': LazyComponent<typeof import("vee-validate")['ErrorMessage']>
  'LazyField': LazyComponent<typeof import("vee-validate")['Field']>
  'LazyFieldArray': LazyComponent<typeof import("vee-validate")['FieldArray']>
  'LazyForm': LazyComponent<typeof import("vee-validate")['Form']>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/pages/runtime/page")['default']>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  'LazyLink': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Link']>
  'LazyBase': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Base']>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Title']>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Meta']>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Style']>
  'LazyHead': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Head']>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Html']>
  'LazyBody': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Body']>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
