
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AppFooter: typeof import("../app/components/app/footer.vue")['default']
export const AppHeader: typeof import("../app/components/app/header.vue")['default']
export const AppHomepageHeader: typeof import("../app/components/app/homepage-header.vue")['default']
export const AuthLoginForm: typeof import("../app/components/auth/login-form.vue")['default']
export const CommonLanguageSwitcher: typeof import("../app/components/common/language-switcher.vue")['default']
export const ContactMessageForm: typeof import("../app/components/contact/message-form.vue")['default']
export const DashboardSidebarMenu: typeof import("../app/components/dashboard/sidebar-menu.vue")['default']
export const DashboardUserDropdown: typeof import("../app/components/dashboard/user-dropdown.vue")['default']
export const GalleryCollectionGrid: typeof import("../app/components/gallery/collection-grid.vue")['default']
export const GalleryDetailDialog: typeof import("../app/components/gallery/detail-dialog.vue")['default']
export const GalleryDetailImageGrid: typeof import("../app/components/gallery/detail-image-grid.vue")['default']
export const GalleryFilterButton: typeof import("../app/components/gallery/filter-button.vue")['default']
export const GalleryDetailHero: typeof import("../app/components/gallery/gallery-detail-hero.vue")['default']
export const GalleryHeaderFilter: typeof import("../app/components/gallery/header-filter.vue")['default']
export const GalleryHeader: typeof import("../app/components/gallery/header.vue")['default']
export const GalleryPagination: typeof import("../app/components/gallery/pagination.vue")['default']
export const HomepageHeroCarousel: typeof import("../app/components/homepage/hero-carousel.vue")['default']
export const HomepageJourneySlider: typeof import("../app/components/homepage/journey-slider.vue")['default']
export const IconInstagram: typeof import("../app/components/icon/instagram.vue")['default']
export const IconInstagram1: typeof import("../app/components/icon/instagram1.vue")['default']
export const IconInstagram2: typeof import("../app/components/icon/instagram2.vue")['default']
export const IconInstagram3: typeof import("../app/components/icon/instagram3.vue")['default']
export const IconTelegram: typeof import("../app/components/icon/telegram.vue")['default']
export const IconTiktok: typeof import("../app/components/icon/tiktok.vue")['default']
export const IconWhatsapp: typeof import("../app/components/icon/whatsapp.vue")['default']
export const ManageAboutContent: typeof import("../app/components/manage-about/content.vue")['default']
export const ManageAboutForm: typeof import("../app/components/manage-about/form.vue")['default']
export const ManageAboutSchema: typeof import("../app/components/manage-about/schema")['default']
export const ManageAboutTable: typeof import("../app/components/manage-about/table.vue")['default']
export const ManageCategoryContent: typeof import("../app/components/manage-category/content.vue")['default']
export const ManageCategoryForm: typeof import("../app/components/manage-category/form.vue")['default']
export const ManageCategorySchema: typeof import("../app/components/manage-category/schema")['default']
export const ManageCategoryTable: typeof import("../app/components/manage-category/table.vue")['default']
export const ManageExploreDetailContent: typeof import("../app/components/manage-explore-detail/content.vue")['default']
export const ManageExploreImagesContent: typeof import("../app/components/manage-explore-images/content.vue")['default']
export const ManageExploreContent: typeof import("../app/components/manage-explore/content.vue")['default']
export const ManageExploreForm: typeof import("../app/components/manage-explore/form.vue")['default']
export const ManageExploreSchema: typeof import("../app/components/manage-explore/schema")['default']
export const ManageExploreTable: typeof import("../app/components/manage-explore/table.vue")['default']
export const ManageGalleryDetailContent: typeof import("../app/components/manage-gallery-detail/content.vue")['default']
export const ManageGalleryDetailForm: typeof import("../app/components/manage-gallery-detail/form.vue")['default']
export const ManageGalleryDetailSchema: typeof import("../app/components/manage-gallery-detail/schema")['default']
export const ManageGalleryDetailTable: typeof import("../app/components/manage-gallery-detail/table.vue")['default']
export const ManageGalleryContent: typeof import("../app/components/manage-gallery/content.vue")['default']
export const ManageGalleryForm: typeof import("../app/components/manage-gallery/form.vue")['default']
export const ManageGallerySchema: typeof import("../app/components/manage-gallery/schema")['default']
export const ManageGalleryTable: typeof import("../app/components/manage-gallery/table.vue")['default']
export const ManageJourneyContent: typeof import("../app/components/manage-journey/content.vue")['default']
export const ManageJourneyForm: typeof import("../app/components/manage-journey/form.vue")['default']
export const ManageJourneySchema: typeof import("../app/components/manage-journey/schema")['default']
export const ManageJourneyTable: typeof import("../app/components/manage-journey/table.vue")['default']
export const ManageSocialMediaContent: typeof import("../app/components/manage-social-media/content.vue")['default']
export const ManageSocialMediaForm: typeof import("../app/components/manage-social-media/form.vue")['default']
export const ManageSocialMediaSchema: typeof import("../app/components/manage-social-media/schema")['default']
export const UiVueSonner: typeof import("../app/components/ui/VueSonner.client.vue")['default']
export const UiAccordion: typeof import("../app/components/ui/accordion/accordion.vue")['default']
export const UiAccordionContent: typeof import("../app/components/ui/accordion/content.vue")['default']
export const UiAccordionHeader: typeof import("../app/components/ui/accordion/header.vue")['default']
export const UiAccordionItem: typeof import("../app/components/ui/accordion/item.vue")['default']
export const UiAccordionTrigger: typeof import("../app/components/ui/accordion/trigger.vue")['default']
export const UiAutoCompleteAnchor: typeof import("../app/components/ui/auto-complete/anchor.vue")['default']
export const UiAutoCompleteArrow: typeof import("../app/components/ui/auto-complete/arrow.vue")['default']
export const UiAutoComplete: typeof import("../app/components/ui/auto-complete/auto-complete.vue")['default']
export const UiAutoCompleteCancel: typeof import("../app/components/ui/auto-complete/cancel.vue")['default']
export const UiAutoCompleteContent: typeof import("../app/components/ui/auto-complete/content.vue")['default']
export const UiAutoCompleteEmpty: typeof import("../app/components/ui/auto-complete/empty.vue")['default']
export const UiAutoCompleteGroup: typeof import("../app/components/ui/auto-complete/group.vue")['default']
export const UiAutoCompleteInput: typeof import("../app/components/ui/auto-complete/input.vue")['default']
export const UiAutoCompleteItemIndicator: typeof import("../app/components/ui/auto-complete/item-indicator.vue")['default']
export const UiAutoCompleteItem: typeof import("../app/components/ui/auto-complete/item.vue")['default']
export const UiAutoCompleteLabel: typeof import("../app/components/ui/auto-complete/label.vue")['default']
export const UiAutoCompletePortal: typeof import("../app/components/ui/auto-complete/portal.vue")['default']
export const UiAutoCompleteSeparator: typeof import("../app/components/ui/auto-complete/separator.vue")['default']
export const UiAutoCompleteTrigger: typeof import("../app/components/ui/auto-complete/trigger.vue")['default']
export const UiAutoCompleteViewport: typeof import("../app/components/ui/auto-complete/viewport.vue")['default']
export const UiBreadcrumbs: typeof import("../app/components/ui/breadcrumbs.vue")['default']
export const UiButton: typeof import("../app/components/ui/button.vue")['default']
export const UiCard: typeof import("../app/components/ui/card/card.vue")['default']
export const UiCardContent: typeof import("../app/components/ui/card/content.vue")['default']
export const UiCardDescription: typeof import("../app/components/ui/card/description.vue")['default']
export const UiCardFooter: typeof import("../app/components/ui/card/footer.vue")['default']
export const UiCardHeader: typeof import("../app/components/ui/card/header.vue")['default']
export const UiCardTitle: typeof import("../app/components/ui/card/title.vue")['default']
export const UiCategorySelect: typeof import("../app/components/ui/category-select.client.vue")['default']
export const UiCommandCancel: typeof import("../app/components/ui/command/cancel.vue")['default']
export const UiCommand: typeof import("../app/components/ui/command/command.vue")['default']
export const UiCommandDialog: typeof import("../app/components/ui/command/dialog.vue")['default']
export const UiCommandEmpty: typeof import("../app/components/ui/command/empty.vue")['default']
export const UiCommandGroup: typeof import("../app/components/ui/command/group.vue")['default']
export const UiCommandInput: typeof import("../app/components/ui/command/input.vue")['default']
export const UiCommandItem: typeof import("../app/components/ui/command/item.vue")['default']
export const UiCommandLabel: typeof import("../app/components/ui/command/label.vue")['default']
export const UiCommandList: typeof import("../app/components/ui/command/list.vue")['default']
export const UiCommandSeparator: typeof import("../app/components/ui/command/separator.vue")['default']
export const UiCommandShortcut: typeof import("../app/components/ui/command/shortcut.vue")['default']
export const UiConfirmDialog: typeof import("../app/components/ui/confirm-dialog.client.vue")['default']
export const UiContainer: typeof import("../app/components/ui/container.vue")['default']
export const UiDialogClose: typeof import("../app/components/ui/dialog/close.vue")['default']
export const UiDialogContent: typeof import("../app/components/ui/dialog/content.vue")['default']
export const UiDialogDescription: typeof import("../app/components/ui/dialog/description.vue")['default']
export const UiDialog: typeof import("../app/components/ui/dialog/dialog.vue")['default']
export const UiDialogFooter: typeof import("../app/components/ui/dialog/footer.vue")['default']
export const UiDialogHeader: typeof import("../app/components/ui/dialog/header.vue")['default']
export const UiDialogOverlay: typeof import("../app/components/ui/dialog/overlay.vue")['default']
export const UiDialogPortal: typeof import("../app/components/ui/dialog/portal.vue")['default']
export const UiDialogTitle: typeof import("../app/components/ui/dialog/title.vue")['default']
export const UiDialogTrigger: typeof import("../app/components/ui/dialog/trigger.vue")['default']
export const UiDropdownMenuArrow: typeof import("../app/components/ui/dropdown-menu/arrow.vue")['default']
export const UiDropdownMenuCheckboxItem: typeof import("../app/components/ui/dropdown-menu/checkbox-item.vue")['default']
export const UiDropdownMenuContent: typeof import("../app/components/ui/dropdown-menu/content.vue")['default']
export const UiDropdownMenu: typeof import("../app/components/ui/dropdown-menu/dropdown-menu.vue")['default']
export const UiDropdownMenuGroup: typeof import("../app/components/ui/dropdown-menu/group.vue")['default']
export const UiDropdownMenuItemIndicator: typeof import("../app/components/ui/dropdown-menu/item-indicator.vue")['default']
export const UiDropdownMenuItem: typeof import("../app/components/ui/dropdown-menu/item.vue")['default']
export const UiDropdownMenuLabel: typeof import("../app/components/ui/dropdown-menu/label.vue")['default']
export const UiDropdownMenuPortal: typeof import("../app/components/ui/dropdown-menu/portal.vue")['default']
export const UiDropdownMenuRadioGroup: typeof import("../app/components/ui/dropdown-menu/radio-group.vue")['default']
export const UiDropdownMenuRadioItem: typeof import("../app/components/ui/dropdown-menu/radio-item.vue")['default']
export const UiDropdownMenuSeparator: typeof import("../app/components/ui/dropdown-menu/separator.vue")['default']
export const UiDropdownMenuShortcut: typeof import("../app/components/ui/dropdown-menu/shortcut.vue")['default']
export const UiDropdownMenuSubContent: typeof import("../app/components/ui/dropdown-menu/sub-content.vue")['default']
export const UiDropdownMenuSubTrigger: typeof import("../app/components/ui/dropdown-menu/sub-trigger.vue")['default']
export const UiDropdownMenuSub: typeof import("../app/components/ui/dropdown-menu/sub.vue")['default']
export const UiDropdownMenuTrigger: typeof import("../app/components/ui/dropdown-menu/trigger.vue")['default']
export const UiDropfile: typeof import("../app/components/ui/dropfile.vue")['default']
export const UiFormControl: typeof import("../app/components/ui/form/control.vue")['default']
export const UiFormDescription: typeof import("../app/components/ui/form/description.vue")['default']
export const UiFormFloatingItem: typeof import("../app/components/ui/form/floating-item.vue")['default']
export const UiFormItem: typeof import("../app/components/ui/form/item.vue")['default']
export const UiFormLabel: typeof import("../app/components/ui/form/label.vue")['default']
export const UiFormMessage: typeof import("../app/components/ui/form/message.vue")['default']
export const UiImagePreview: typeof import("../app/components/ui/image-preview.vue")['default']
export const UiInput: typeof import("../app/components/ui/input.vue")['default']
export const UiLabel: typeof import("../app/components/ui/label.vue")['default']
export const UiNavbar: typeof import("../app/components/ui/navbar.vue")['default']
export const UiPaginationNumberControl: typeof import("../app/components/ui/pagination/number-control.vue")['default']
export const UiPagination: typeof import("../app/components/ui/pagination/pagination.vue")['default']
export const UiPaginationPerPage: typeof import("../app/components/ui/pagination/per-page.vue")['default']
export const UiPopoverAnchor: typeof import("../app/components/ui/popover/anchor.vue")['default']
export const UiPopoverArrow: typeof import("../app/components/ui/popover/arrow.vue")['default']
export const UiPopoverClose: typeof import("../app/components/ui/popover/close.vue")['default']
export const UiPopoverContent: typeof import("../app/components/ui/popover/content.vue")['default']
export const UiPopover: typeof import("../app/components/ui/popover/popover.vue")['default']
export const UiPopoverPortal: typeof import("../app/components/ui/popover/portal.vue")['default']
export const UiPopoverTrigger: typeof import("../app/components/ui/popover/trigger.vue")['default']
export const UiPopoverX: typeof import("../app/components/ui/popover/x.vue")['default']
export const UiSelectArrow: typeof import("../app/components/ui/select/arrow.vue")['default']
export const UiSelectContent: typeof import("../app/components/ui/select/content.vue")['default']
export const UiSelectGroup: typeof import("../app/components/ui/select/group.vue")['default']
export const UiSelectIcon: typeof import("../app/components/ui/select/icon.vue")['default']
export const UiSelectItemIndicator: typeof import("../app/components/ui/select/item-indicator.vue")['default']
export const UiSelectItemText: typeof import("../app/components/ui/select/item-text.vue")['default']
export const UiSelectItem: typeof import("../app/components/ui/select/item.vue")['default']
export const UiSelectLabel: typeof import("../app/components/ui/select/label.vue")['default']
export const UiSelectPortal: typeof import("../app/components/ui/select/portal.vue")['default']
export const UiSelectScrollDownButton: typeof import("../app/components/ui/select/scroll-down-button.vue")['default']
export const UiSelectScrollUpButton: typeof import("../app/components/ui/select/scroll-up-button.vue")['default']
export const UiSelect: typeof import("../app/components/ui/select/select.vue")['default']
export const UiSelectSeparator: typeof import("../app/components/ui/select/separator.vue")['default']
export const UiSelectTrigger: typeof import("../app/components/ui/select/trigger.vue")['default']
export const UiSelectValue: typeof import("../app/components/ui/select/value.vue")['default']
export const UiSelectViewport: typeof import("../app/components/ui/select/viewport.vue")['default']
export const UiSeparator: typeof import("../app/components/ui/separator.vue")['default']
export const UiSheetClose: typeof import("../app/components/ui/sheet/close.vue")['default']
export const UiSheetContent: typeof import("../app/components/ui/sheet/content.vue")['default']
export const UiSheetDescription: typeof import("../app/components/ui/sheet/description.vue")['default']
export const UiSheetFooter: typeof import("../app/components/ui/sheet/footer.vue")['default']
export const UiSheetHeader: typeof import("../app/components/ui/sheet/header.vue")['default']
export const UiSheetOverlay: typeof import("../app/components/ui/sheet/overlay.vue")['default']
export const UiSheetPortal: typeof import("../app/components/ui/sheet/portal.vue")['default']
export const UiSheet: typeof import("../app/components/ui/sheet/sheet.vue")['default']
export const UiSheetTitle: typeof import("../app/components/ui/sheet/title.vue")['default']
export const UiSheetTrigger: typeof import("../app/components/ui/sheet/trigger.vue")['default']
export const UiSheetX: typeof import("../app/components/ui/sheet/x.vue")['default']
export const UiSidebarContent: typeof import("../app/components/ui/sidebar/content.vue")['default']
export const UiSidebarFooter: typeof import("../app/components/ui/sidebar/footer.vue")['default']
export const UiSidebarGroupAction: typeof import("../app/components/ui/sidebar/group-action.vue")['default']
export const UiSidebarGroupContent: typeof import("../app/components/ui/sidebar/group-content.vue")['default']
export const UiSidebarGroupLabel: typeof import("../app/components/ui/sidebar/group-label.vue")['default']
export const UiSidebarGroup: typeof import("../app/components/ui/sidebar/group.vue")['default']
export const UiSidebarHeader: typeof import("../app/components/ui/sidebar/header.vue")['default']
export const UiSidebarInput: typeof import("../app/components/ui/sidebar/input.vue")['default']
export const UiSidebarInset: typeof import("../app/components/ui/sidebar/inset.vue")['default']
export const UiSidebarMenuAction: typeof import("../app/components/ui/sidebar/menu-action.vue")['default']
export const UiSidebarMenuBadge: typeof import("../app/components/ui/sidebar/menu-badge.vue")['default']
export const UiSidebarMenuButtonChild: typeof import("../app/components/ui/sidebar/menu-button-child.vue")['default']
export const UiSidebarMenuButton: typeof import("../app/components/ui/sidebar/menu-button.vue")['default']
export const UiSidebarMenuItem: typeof import("../app/components/ui/sidebar/menu-item.vue")['default']
export const UiSidebarMenuSkeleton: typeof import("../app/components/ui/sidebar/menu-skeleton.vue")['default']
export const UiSidebarMenuSubButton: typeof import("../app/components/ui/sidebar/menu-sub-button.vue")['default']
export const UiSidebarMenuSubItem: typeof import("../app/components/ui/sidebar/menu-sub-item.vue")['default']
export const UiSidebarMenuSub: typeof import("../app/components/ui/sidebar/menu-sub.vue")['default']
export const UiSidebarMenu: typeof import("../app/components/ui/sidebar/menu.vue")['default']
export const UiSidebarProvider: typeof import("../app/components/ui/sidebar/provider.vue")['default']
export const UiSidebarRail: typeof import("../app/components/ui/sidebar/rail.vue")['default']
export const UiSidebarSeparator: typeof import("../app/components/ui/sidebar/separator.vue")['default']
export const UiSidebar: typeof import("../app/components/ui/sidebar/sidebar.vue")['default']
export const UiSidebarTrigger: typeof import("../app/components/ui/sidebar/trigger.vue")['default']
export const UiTableAction: typeof import("../app/components/ui/table/action.vue")['default']
export const UiTableContainer: typeof import("../app/components/ui/table/container.vue")['default']
export const UiTableData: typeof import("../app/components/ui/table/data.vue")['default']
export const UiTableHead: typeof import("../app/components/ui/table/head.vue")['default']
export const UiTableRow: typeof import("../app/components/ui/table/row.vue")['default']
export const UiTableSearch: typeof import("../app/components/ui/table/search.vue")['default']
export const UiTable: typeof import("../app/components/ui/table/table.vue")['default']
export const UiTextarea: typeof import("../app/components/ui/textarea.vue")['default']
export const UiTiptap: typeof import("../app/components/ui/tiptap.client.vue")['default']
export const UiTooltipArrow: typeof import("../app/components/ui/tooltip/arrow.vue")['default']
export const UiTooltipContent: typeof import("../app/components/ui/tooltip/content.vue")['default']
export const UiTooltipPortal: typeof import("../app/components/ui/tooltip/portal.vue")['default']
export const UiTooltipProvider: typeof import("../app/components/ui/tooltip/provider.vue")['default']
export const UiTooltip: typeof import("../app/components/ui/tooltip/tooltip.vue")['default']
export const UiTooltipTrigger: typeof import("../app/components/ui/tooltip/trigger.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.3.5_vite@7.1.9_@types+node@24.10.1_jiti@2.6.1_lightningcss_d91a7470f0b7d900e7fd19ead4b8541a/node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const TiptapEditorContent: typeof import("@tiptap/vue-3")['EditorContent']
export const TiptapFloatingMenu: typeof import("@tiptap/vue-3")['FloatingMenu']
export const TiptapBubbleMenu: typeof import("@tiptap/vue-3")['BubbleMenu']
export const ErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const Field: typeof import("vee-validate")['Field']
export const FieldArray: typeof import("vee-validate")['FieldArray']
export const Form: typeof import("vee-validate")['Form']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAppFooter: LazyComponent<typeof import("../app/components/app/footer.vue")['default']>
export const LazyAppHeader: LazyComponent<typeof import("../app/components/app/header.vue")['default']>
export const LazyAppHomepageHeader: LazyComponent<typeof import("../app/components/app/homepage-header.vue")['default']>
export const LazyAuthLoginForm: LazyComponent<typeof import("../app/components/auth/login-form.vue")['default']>
export const LazyCommonLanguageSwitcher: LazyComponent<typeof import("../app/components/common/language-switcher.vue")['default']>
export const LazyContactMessageForm: LazyComponent<typeof import("../app/components/contact/message-form.vue")['default']>
export const LazyDashboardSidebarMenu: LazyComponent<typeof import("../app/components/dashboard/sidebar-menu.vue")['default']>
export const LazyDashboardUserDropdown: LazyComponent<typeof import("../app/components/dashboard/user-dropdown.vue")['default']>
export const LazyGalleryCollectionGrid: LazyComponent<typeof import("../app/components/gallery/collection-grid.vue")['default']>
export const LazyGalleryDetailDialog: LazyComponent<typeof import("../app/components/gallery/detail-dialog.vue")['default']>
export const LazyGalleryDetailImageGrid: LazyComponent<typeof import("../app/components/gallery/detail-image-grid.vue")['default']>
export const LazyGalleryFilterButton: LazyComponent<typeof import("../app/components/gallery/filter-button.vue")['default']>
export const LazyGalleryDetailHero: LazyComponent<typeof import("../app/components/gallery/gallery-detail-hero.vue")['default']>
export const LazyGalleryHeaderFilter: LazyComponent<typeof import("../app/components/gallery/header-filter.vue")['default']>
export const LazyGalleryHeader: LazyComponent<typeof import("../app/components/gallery/header.vue")['default']>
export const LazyGalleryPagination: LazyComponent<typeof import("../app/components/gallery/pagination.vue")['default']>
export const LazyHomepageHeroCarousel: LazyComponent<typeof import("../app/components/homepage/hero-carousel.vue")['default']>
export const LazyHomepageJourneySlider: LazyComponent<typeof import("../app/components/homepage/journey-slider.vue")['default']>
export const LazyIconInstagram: LazyComponent<typeof import("../app/components/icon/instagram.vue")['default']>
export const LazyIconInstagram1: LazyComponent<typeof import("../app/components/icon/instagram1.vue")['default']>
export const LazyIconInstagram2: LazyComponent<typeof import("../app/components/icon/instagram2.vue")['default']>
export const LazyIconInstagram3: LazyComponent<typeof import("../app/components/icon/instagram3.vue")['default']>
export const LazyIconTelegram: LazyComponent<typeof import("../app/components/icon/telegram.vue")['default']>
export const LazyIconTiktok: LazyComponent<typeof import("../app/components/icon/tiktok.vue")['default']>
export const LazyIconWhatsapp: LazyComponent<typeof import("../app/components/icon/whatsapp.vue")['default']>
export const LazyManageAboutContent: LazyComponent<typeof import("../app/components/manage-about/content.vue")['default']>
export const LazyManageAboutForm: LazyComponent<typeof import("../app/components/manage-about/form.vue")['default']>
export const LazyManageAboutSchema: LazyComponent<typeof import("../app/components/manage-about/schema")['default']>
export const LazyManageAboutTable: LazyComponent<typeof import("../app/components/manage-about/table.vue")['default']>
export const LazyManageCategoryContent: LazyComponent<typeof import("../app/components/manage-category/content.vue")['default']>
export const LazyManageCategoryForm: LazyComponent<typeof import("../app/components/manage-category/form.vue")['default']>
export const LazyManageCategorySchema: LazyComponent<typeof import("../app/components/manage-category/schema")['default']>
export const LazyManageCategoryTable: LazyComponent<typeof import("../app/components/manage-category/table.vue")['default']>
export const LazyManageExploreDetailContent: LazyComponent<typeof import("../app/components/manage-explore-detail/content.vue")['default']>
export const LazyManageExploreImagesContent: LazyComponent<typeof import("../app/components/manage-explore-images/content.vue")['default']>
export const LazyManageExploreContent: LazyComponent<typeof import("../app/components/manage-explore/content.vue")['default']>
export const LazyManageExploreForm: LazyComponent<typeof import("../app/components/manage-explore/form.vue")['default']>
export const LazyManageExploreSchema: LazyComponent<typeof import("../app/components/manage-explore/schema")['default']>
export const LazyManageExploreTable: LazyComponent<typeof import("../app/components/manage-explore/table.vue")['default']>
export const LazyManageGalleryDetailContent: LazyComponent<typeof import("../app/components/manage-gallery-detail/content.vue")['default']>
export const LazyManageGalleryDetailForm: LazyComponent<typeof import("../app/components/manage-gallery-detail/form.vue")['default']>
export const LazyManageGalleryDetailSchema: LazyComponent<typeof import("../app/components/manage-gallery-detail/schema")['default']>
export const LazyManageGalleryDetailTable: LazyComponent<typeof import("../app/components/manage-gallery-detail/table.vue")['default']>
export const LazyManageGalleryContent: LazyComponent<typeof import("../app/components/manage-gallery/content.vue")['default']>
export const LazyManageGalleryForm: LazyComponent<typeof import("../app/components/manage-gallery/form.vue")['default']>
export const LazyManageGallerySchema: LazyComponent<typeof import("../app/components/manage-gallery/schema")['default']>
export const LazyManageGalleryTable: LazyComponent<typeof import("../app/components/manage-gallery/table.vue")['default']>
export const LazyManageJourneyContent: LazyComponent<typeof import("../app/components/manage-journey/content.vue")['default']>
export const LazyManageJourneyForm: LazyComponent<typeof import("../app/components/manage-journey/form.vue")['default']>
export const LazyManageJourneySchema: LazyComponent<typeof import("../app/components/manage-journey/schema")['default']>
export const LazyManageJourneyTable: LazyComponent<typeof import("../app/components/manage-journey/table.vue")['default']>
export const LazyManageSocialMediaContent: LazyComponent<typeof import("../app/components/manage-social-media/content.vue")['default']>
export const LazyManageSocialMediaForm: LazyComponent<typeof import("../app/components/manage-social-media/form.vue")['default']>
export const LazyManageSocialMediaSchema: LazyComponent<typeof import("../app/components/manage-social-media/schema")['default']>
export const LazyUiVueSonner: LazyComponent<typeof import("../app/components/ui/VueSonner.client.vue")['default']>
export const LazyUiAccordion: LazyComponent<typeof import("../app/components/ui/accordion/accordion.vue")['default']>
export const LazyUiAccordionContent: LazyComponent<typeof import("../app/components/ui/accordion/content.vue")['default']>
export const LazyUiAccordionHeader: LazyComponent<typeof import("../app/components/ui/accordion/header.vue")['default']>
export const LazyUiAccordionItem: LazyComponent<typeof import("../app/components/ui/accordion/item.vue")['default']>
export const LazyUiAccordionTrigger: LazyComponent<typeof import("../app/components/ui/accordion/trigger.vue")['default']>
export const LazyUiAutoCompleteAnchor: LazyComponent<typeof import("../app/components/ui/auto-complete/anchor.vue")['default']>
export const LazyUiAutoCompleteArrow: LazyComponent<typeof import("../app/components/ui/auto-complete/arrow.vue")['default']>
export const LazyUiAutoComplete: LazyComponent<typeof import("../app/components/ui/auto-complete/auto-complete.vue")['default']>
export const LazyUiAutoCompleteCancel: LazyComponent<typeof import("../app/components/ui/auto-complete/cancel.vue")['default']>
export const LazyUiAutoCompleteContent: LazyComponent<typeof import("../app/components/ui/auto-complete/content.vue")['default']>
export const LazyUiAutoCompleteEmpty: LazyComponent<typeof import("../app/components/ui/auto-complete/empty.vue")['default']>
export const LazyUiAutoCompleteGroup: LazyComponent<typeof import("../app/components/ui/auto-complete/group.vue")['default']>
export const LazyUiAutoCompleteInput: LazyComponent<typeof import("../app/components/ui/auto-complete/input.vue")['default']>
export const LazyUiAutoCompleteItemIndicator: LazyComponent<typeof import("../app/components/ui/auto-complete/item-indicator.vue")['default']>
export const LazyUiAutoCompleteItem: LazyComponent<typeof import("../app/components/ui/auto-complete/item.vue")['default']>
export const LazyUiAutoCompleteLabel: LazyComponent<typeof import("../app/components/ui/auto-complete/label.vue")['default']>
export const LazyUiAutoCompletePortal: LazyComponent<typeof import("../app/components/ui/auto-complete/portal.vue")['default']>
export const LazyUiAutoCompleteSeparator: LazyComponent<typeof import("../app/components/ui/auto-complete/separator.vue")['default']>
export const LazyUiAutoCompleteTrigger: LazyComponent<typeof import("../app/components/ui/auto-complete/trigger.vue")['default']>
export const LazyUiAutoCompleteViewport: LazyComponent<typeof import("../app/components/ui/auto-complete/viewport.vue")['default']>
export const LazyUiBreadcrumbs: LazyComponent<typeof import("../app/components/ui/breadcrumbs.vue")['default']>
export const LazyUiButton: LazyComponent<typeof import("../app/components/ui/button.vue")['default']>
export const LazyUiCard: LazyComponent<typeof import("../app/components/ui/card/card.vue")['default']>
export const LazyUiCardContent: LazyComponent<typeof import("../app/components/ui/card/content.vue")['default']>
export const LazyUiCardDescription: LazyComponent<typeof import("../app/components/ui/card/description.vue")['default']>
export const LazyUiCardFooter: LazyComponent<typeof import("../app/components/ui/card/footer.vue")['default']>
export const LazyUiCardHeader: LazyComponent<typeof import("../app/components/ui/card/header.vue")['default']>
export const LazyUiCardTitle: LazyComponent<typeof import("../app/components/ui/card/title.vue")['default']>
export const LazyUiCategorySelect: LazyComponent<typeof import("../app/components/ui/category-select.client.vue")['default']>
export const LazyUiCommandCancel: LazyComponent<typeof import("../app/components/ui/command/cancel.vue")['default']>
export const LazyUiCommand: LazyComponent<typeof import("../app/components/ui/command/command.vue")['default']>
export const LazyUiCommandDialog: LazyComponent<typeof import("../app/components/ui/command/dialog.vue")['default']>
export const LazyUiCommandEmpty: LazyComponent<typeof import("../app/components/ui/command/empty.vue")['default']>
export const LazyUiCommandGroup: LazyComponent<typeof import("../app/components/ui/command/group.vue")['default']>
export const LazyUiCommandInput: LazyComponent<typeof import("../app/components/ui/command/input.vue")['default']>
export const LazyUiCommandItem: LazyComponent<typeof import("../app/components/ui/command/item.vue")['default']>
export const LazyUiCommandLabel: LazyComponent<typeof import("../app/components/ui/command/label.vue")['default']>
export const LazyUiCommandList: LazyComponent<typeof import("../app/components/ui/command/list.vue")['default']>
export const LazyUiCommandSeparator: LazyComponent<typeof import("../app/components/ui/command/separator.vue")['default']>
export const LazyUiCommandShortcut: LazyComponent<typeof import("../app/components/ui/command/shortcut.vue")['default']>
export const LazyUiConfirmDialog: LazyComponent<typeof import("../app/components/ui/confirm-dialog.client.vue")['default']>
export const LazyUiContainer: LazyComponent<typeof import("../app/components/ui/container.vue")['default']>
export const LazyUiDialogClose: LazyComponent<typeof import("../app/components/ui/dialog/close.vue")['default']>
export const LazyUiDialogContent: LazyComponent<typeof import("../app/components/ui/dialog/content.vue")['default']>
export const LazyUiDialogDescription: LazyComponent<typeof import("../app/components/ui/dialog/description.vue")['default']>
export const LazyUiDialog: LazyComponent<typeof import("../app/components/ui/dialog/dialog.vue")['default']>
export const LazyUiDialogFooter: LazyComponent<typeof import("../app/components/ui/dialog/footer.vue")['default']>
export const LazyUiDialogHeader: LazyComponent<typeof import("../app/components/ui/dialog/header.vue")['default']>
export const LazyUiDialogOverlay: LazyComponent<typeof import("../app/components/ui/dialog/overlay.vue")['default']>
export const LazyUiDialogPortal: LazyComponent<typeof import("../app/components/ui/dialog/portal.vue")['default']>
export const LazyUiDialogTitle: LazyComponent<typeof import("../app/components/ui/dialog/title.vue")['default']>
export const LazyUiDialogTrigger: LazyComponent<typeof import("../app/components/ui/dialog/trigger.vue")['default']>
export const LazyUiDropdownMenuArrow: LazyComponent<typeof import("../app/components/ui/dropdown-menu/arrow.vue")['default']>
export const LazyUiDropdownMenuCheckboxItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/checkbox-item.vue")['default']>
export const LazyUiDropdownMenuContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/content.vue")['default']>
export const LazyUiDropdownMenu: LazyComponent<typeof import("../app/components/ui/dropdown-menu/dropdown-menu.vue")['default']>
export const LazyUiDropdownMenuGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/group.vue")['default']>
export const LazyUiDropdownMenuItemIndicator: LazyComponent<typeof import("../app/components/ui/dropdown-menu/item-indicator.vue")['default']>
export const LazyUiDropdownMenuItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/item.vue")['default']>
export const LazyUiDropdownMenuLabel: LazyComponent<typeof import("../app/components/ui/dropdown-menu/label.vue")['default']>
export const LazyUiDropdownMenuPortal: LazyComponent<typeof import("../app/components/ui/dropdown-menu/portal.vue")['default']>
export const LazyUiDropdownMenuRadioGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/radio-group.vue")['default']>
export const LazyUiDropdownMenuRadioItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/radio-item.vue")['default']>
export const LazyUiDropdownMenuSeparator: LazyComponent<typeof import("../app/components/ui/dropdown-menu/separator.vue")['default']>
export const LazyUiDropdownMenuShortcut: LazyComponent<typeof import("../app/components/ui/dropdown-menu/shortcut.vue")['default']>
export const LazyUiDropdownMenuSubContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/sub-content.vue")['default']>
export const LazyUiDropdownMenuSubTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/sub-trigger.vue")['default']>
export const LazyUiDropdownMenuSub: LazyComponent<typeof import("../app/components/ui/dropdown-menu/sub.vue")['default']>
export const LazyUiDropdownMenuTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/trigger.vue")['default']>
export const LazyUiDropfile: LazyComponent<typeof import("../app/components/ui/dropfile.vue")['default']>
export const LazyUiFormControl: LazyComponent<typeof import("../app/components/ui/form/control.vue")['default']>
export const LazyUiFormDescription: LazyComponent<typeof import("../app/components/ui/form/description.vue")['default']>
export const LazyUiFormFloatingItem: LazyComponent<typeof import("../app/components/ui/form/floating-item.vue")['default']>
export const LazyUiFormItem: LazyComponent<typeof import("../app/components/ui/form/item.vue")['default']>
export const LazyUiFormLabel: LazyComponent<typeof import("../app/components/ui/form/label.vue")['default']>
export const LazyUiFormMessage: LazyComponent<typeof import("../app/components/ui/form/message.vue")['default']>
export const LazyUiImagePreview: LazyComponent<typeof import("../app/components/ui/image-preview.vue")['default']>
export const LazyUiInput: LazyComponent<typeof import("../app/components/ui/input.vue")['default']>
export const LazyUiLabel: LazyComponent<typeof import("../app/components/ui/label.vue")['default']>
export const LazyUiNavbar: LazyComponent<typeof import("../app/components/ui/navbar.vue")['default']>
export const LazyUiPaginationNumberControl: LazyComponent<typeof import("../app/components/ui/pagination/number-control.vue")['default']>
export const LazyUiPagination: LazyComponent<typeof import("../app/components/ui/pagination/pagination.vue")['default']>
export const LazyUiPaginationPerPage: LazyComponent<typeof import("../app/components/ui/pagination/per-page.vue")['default']>
export const LazyUiPopoverAnchor: LazyComponent<typeof import("../app/components/ui/popover/anchor.vue")['default']>
export const LazyUiPopoverArrow: LazyComponent<typeof import("../app/components/ui/popover/arrow.vue")['default']>
export const LazyUiPopoverClose: LazyComponent<typeof import("../app/components/ui/popover/close.vue")['default']>
export const LazyUiPopoverContent: LazyComponent<typeof import("../app/components/ui/popover/content.vue")['default']>
export const LazyUiPopover: LazyComponent<typeof import("../app/components/ui/popover/popover.vue")['default']>
export const LazyUiPopoverPortal: LazyComponent<typeof import("../app/components/ui/popover/portal.vue")['default']>
export const LazyUiPopoverTrigger: LazyComponent<typeof import("../app/components/ui/popover/trigger.vue")['default']>
export const LazyUiPopoverX: LazyComponent<typeof import("../app/components/ui/popover/x.vue")['default']>
export const LazyUiSelectArrow: LazyComponent<typeof import("../app/components/ui/select/arrow.vue")['default']>
export const LazyUiSelectContent: LazyComponent<typeof import("../app/components/ui/select/content.vue")['default']>
export const LazyUiSelectGroup: LazyComponent<typeof import("../app/components/ui/select/group.vue")['default']>
export const LazyUiSelectIcon: LazyComponent<typeof import("../app/components/ui/select/icon.vue")['default']>
export const LazyUiSelectItemIndicator: LazyComponent<typeof import("../app/components/ui/select/item-indicator.vue")['default']>
export const LazyUiSelectItemText: LazyComponent<typeof import("../app/components/ui/select/item-text.vue")['default']>
export const LazyUiSelectItem: LazyComponent<typeof import("../app/components/ui/select/item.vue")['default']>
export const LazyUiSelectLabel: LazyComponent<typeof import("../app/components/ui/select/label.vue")['default']>
export const LazyUiSelectPortal: LazyComponent<typeof import("../app/components/ui/select/portal.vue")['default']>
export const LazyUiSelectScrollDownButton: LazyComponent<typeof import("../app/components/ui/select/scroll-down-button.vue")['default']>
export const LazyUiSelectScrollUpButton: LazyComponent<typeof import("../app/components/ui/select/scroll-up-button.vue")['default']>
export const LazyUiSelect: LazyComponent<typeof import("../app/components/ui/select/select.vue")['default']>
export const LazyUiSelectSeparator: LazyComponent<typeof import("../app/components/ui/select/separator.vue")['default']>
export const LazyUiSelectTrigger: LazyComponent<typeof import("../app/components/ui/select/trigger.vue")['default']>
export const LazyUiSelectValue: LazyComponent<typeof import("../app/components/ui/select/value.vue")['default']>
export const LazyUiSelectViewport: LazyComponent<typeof import("../app/components/ui/select/viewport.vue")['default']>
export const LazyUiSeparator: LazyComponent<typeof import("../app/components/ui/separator.vue")['default']>
export const LazyUiSheetClose: LazyComponent<typeof import("../app/components/ui/sheet/close.vue")['default']>
export const LazyUiSheetContent: LazyComponent<typeof import("../app/components/ui/sheet/content.vue")['default']>
export const LazyUiSheetDescription: LazyComponent<typeof import("../app/components/ui/sheet/description.vue")['default']>
export const LazyUiSheetFooter: LazyComponent<typeof import("../app/components/ui/sheet/footer.vue")['default']>
export const LazyUiSheetHeader: LazyComponent<typeof import("../app/components/ui/sheet/header.vue")['default']>
export const LazyUiSheetOverlay: LazyComponent<typeof import("../app/components/ui/sheet/overlay.vue")['default']>
export const LazyUiSheetPortal: LazyComponent<typeof import("../app/components/ui/sheet/portal.vue")['default']>
export const LazyUiSheet: LazyComponent<typeof import("../app/components/ui/sheet/sheet.vue")['default']>
export const LazyUiSheetTitle: LazyComponent<typeof import("../app/components/ui/sheet/title.vue")['default']>
export const LazyUiSheetTrigger: LazyComponent<typeof import("../app/components/ui/sheet/trigger.vue")['default']>
export const LazyUiSheetX: LazyComponent<typeof import("../app/components/ui/sheet/x.vue")['default']>
export const LazyUiSidebarContent: LazyComponent<typeof import("../app/components/ui/sidebar/content.vue")['default']>
export const LazyUiSidebarFooter: LazyComponent<typeof import("../app/components/ui/sidebar/footer.vue")['default']>
export const LazyUiSidebarGroupAction: LazyComponent<typeof import("../app/components/ui/sidebar/group-action.vue")['default']>
export const LazyUiSidebarGroupContent: LazyComponent<typeof import("../app/components/ui/sidebar/group-content.vue")['default']>
export const LazyUiSidebarGroupLabel: LazyComponent<typeof import("../app/components/ui/sidebar/group-label.vue")['default']>
export const LazyUiSidebarGroup: LazyComponent<typeof import("../app/components/ui/sidebar/group.vue")['default']>
export const LazyUiSidebarHeader: LazyComponent<typeof import("../app/components/ui/sidebar/header.vue")['default']>
export const LazyUiSidebarInput: LazyComponent<typeof import("../app/components/ui/sidebar/input.vue")['default']>
export const LazyUiSidebarInset: LazyComponent<typeof import("../app/components/ui/sidebar/inset.vue")['default']>
export const LazyUiSidebarMenuAction: LazyComponent<typeof import("../app/components/ui/sidebar/menu-action.vue")['default']>
export const LazyUiSidebarMenuBadge: LazyComponent<typeof import("../app/components/ui/sidebar/menu-badge.vue")['default']>
export const LazyUiSidebarMenuButtonChild: LazyComponent<typeof import("../app/components/ui/sidebar/menu-button-child.vue")['default']>
export const LazyUiSidebarMenuButton: LazyComponent<typeof import("../app/components/ui/sidebar/menu-button.vue")['default']>
export const LazyUiSidebarMenuItem: LazyComponent<typeof import("../app/components/ui/sidebar/menu-item.vue")['default']>
export const LazyUiSidebarMenuSkeleton: LazyComponent<typeof import("../app/components/ui/sidebar/menu-skeleton.vue")['default']>
export const LazyUiSidebarMenuSubButton: LazyComponent<typeof import("../app/components/ui/sidebar/menu-sub-button.vue")['default']>
export const LazyUiSidebarMenuSubItem: LazyComponent<typeof import("../app/components/ui/sidebar/menu-sub-item.vue")['default']>
export const LazyUiSidebarMenuSub: LazyComponent<typeof import("../app/components/ui/sidebar/menu-sub.vue")['default']>
export const LazyUiSidebarMenu: LazyComponent<typeof import("../app/components/ui/sidebar/menu.vue")['default']>
export const LazyUiSidebarProvider: LazyComponent<typeof import("../app/components/ui/sidebar/provider.vue")['default']>
export const LazyUiSidebarRail: LazyComponent<typeof import("../app/components/ui/sidebar/rail.vue")['default']>
export const LazyUiSidebarSeparator: LazyComponent<typeof import("../app/components/ui/sidebar/separator.vue")['default']>
export const LazyUiSidebar: LazyComponent<typeof import("../app/components/ui/sidebar/sidebar.vue")['default']>
export const LazyUiSidebarTrigger: LazyComponent<typeof import("../app/components/ui/sidebar/trigger.vue")['default']>
export const LazyUiTableAction: LazyComponent<typeof import("../app/components/ui/table/action.vue")['default']>
export const LazyUiTableContainer: LazyComponent<typeof import("../app/components/ui/table/container.vue")['default']>
export const LazyUiTableData: LazyComponent<typeof import("../app/components/ui/table/data.vue")['default']>
export const LazyUiTableHead: LazyComponent<typeof import("../app/components/ui/table/head.vue")['default']>
export const LazyUiTableRow: LazyComponent<typeof import("../app/components/ui/table/row.vue")['default']>
export const LazyUiTableSearch: LazyComponent<typeof import("../app/components/ui/table/search.vue")['default']>
export const LazyUiTable: LazyComponent<typeof import("../app/components/ui/table/table.vue")['default']>
export const LazyUiTextarea: LazyComponent<typeof import("../app/components/ui/textarea.vue")['default']>
export const LazyUiTiptap: LazyComponent<typeof import("../app/components/ui/tiptap.client.vue")['default']>
export const LazyUiTooltipArrow: LazyComponent<typeof import("../app/components/ui/tooltip/arrow.vue")['default']>
export const LazyUiTooltipContent: LazyComponent<typeof import("../app/components/ui/tooltip/content.vue")['default']>
export const LazyUiTooltipPortal: LazyComponent<typeof import("../app/components/ui/tooltip/portal.vue")['default']>
export const LazyUiTooltipProvider: LazyComponent<typeof import("../app/components/ui/tooltip/provider.vue")['default']>
export const LazyUiTooltip: LazyComponent<typeof import("../app/components/ui/tooltip/tooltip.vue")['default']>
export const LazyUiTooltipTrigger: LazyComponent<typeof import("../app/components/ui/tooltip/trigger.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyIcon: LazyComponent<typeof import("../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.3.5_vite@7.1.9_@types+node@24.10.1_jiti@2.6.1_lightningcss_d91a7470f0b7d900e7fd19ead4b8541a/node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
export const LazyTiptapEditorContent: LazyComponent<typeof import("@tiptap/vue-3")['EditorContent']>
export const LazyTiptapFloatingMenu: LazyComponent<typeof import("@tiptap/vue-3")['FloatingMenu']>
export const LazyTiptapBubbleMenu: LazyComponent<typeof import("@tiptap/vue-3")['BubbleMenu']>
export const LazyErrorMessage: LazyComponent<typeof import("vee-validate")['ErrorMessage']>
export const LazyField: LazyComponent<typeof import("vee-validate")['Field']>
export const LazyFieldArray: LazyComponent<typeof import("vee-validate")['FieldArray']>
export const LazyForm: LazyComponent<typeof import("vee-validate")['Form']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.22_db0@0.3.4_5b4db39832caaa4fa6da828c9ba789fd/node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
